<?php
$allTasks = $this->allTasks;
arsort($allTasks);

$this->title = 'Search Results';
?>

<div class="container mx-auto">
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <div class="flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 pb-4 bg-white dark:bg-gray-900">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Task ID
            </th>
            <th scope="col" class="px-6 py-3">
              Task Name
            </th>
            <th scope="col" class="px-6 py-3">
              Username
            </th>
            <th scope="col" class="px-6 py-3">
              Created Time
            </th>
            <th scope="col" class="px-6 py-3">
              Completed Time
            </th>
            <th scope="col" class="px-6 py-3">
              Status
            </th>
            <th scope="col" class="px-6 py-3">
              Action
            </th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($allTasks as $task) : ?>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
              <td class="px-6 py-4">
                <?php echo $task->id; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->name; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->username; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->create_time; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->completed_time ?? 'Not completed'; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->status; ?>
              </td>
              <td class="px-6 py-4">
                <div class="flex items-center space-x-2">
                  <a href="/task/delete/<?php echo $task->id; ?>" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                    <img width="25" height="25" src="https://img.icons8.com/windows/32/7e22ce/waste.png" alt="waste" />
                  </a>
                  <a href="/task/update/<?php echo $task->id; ?>" data-modal-target="editTask" data-modal-toggle="editTask" class="edit-task-link">
                    <img width="22" height="22" viewBox="0 0 50 50" src="https://img.icons8.com/forma-regular-filled/24/4D4D4D/edit-file.png" alt="edit-file" />
                  </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
